export const apiUrls = {
  //Auth
  login: "Auth/login",
  ResetPassword: "Auth/ResetPassword",
  ProfileUpdate: "Auth/ProfileUpdate",
  ProfileDetails: "Auth/ProfileDetails",
  SettingById: "Common/SettingById",
  UpdateSettingById: "Common/UpdateSettingById",
  ForgetPassword: "Auth/ForgetPassword",
  VerifyForgetPassword: "Auth/VerifyForgetPassword",
  GetAllJobs: "Common/GetAllJobs",
  GetAllDiscount: "Common/GetAllDiscount",
  //Comman Api
  HomePageContent: "Auth/HomePageContent",
  permissionlist: "Module/modules",
  uploadFiles: "Common/FileUpload",
  GetAllJobTitle: "Common/GetAllJobTitle",
  GetAllVendor: "Common/GetAllVendor",
  GetAllMeterial: "Common/GetAllMaterial",
  GetAllProductType: "Common/GetAllProductType",
  GetAllProduct: "Common/GetAllProduct",
  GetAllOption: "Common/GetAllOption",
  GetAllComponent: "Common/GetAllComponent",
  GetAllUnitOfMeasurement: "Common/GetAllUnitOfMeasurement",
  GetAllAddress: "Common/GetAllAddress",
  GetAllRoles: "Common/GetAllRoles",
  GetAllJobType: "Common/GetAllJobType",
  GetAllAssignedPerson: "Common/GetAllAssignedPerson",
  GetAllJobStatus: "Common/GetAllJobStatus",
  GetAllRegion: "Common/GetAllRegion",
  GetAllContact: "Common/GetAllContacts",
  ImportandExport: "ImportandExport/import",
  ExportContacts: "ImportandExport/ExportAll",
  DashBoard: "Common/DashBoard",
  GetAllExpression: "Common/GetAllExpression",
  GetAllExpressionChip:"Common/GetAllExpressionChip",
  GetAllInvoice:"Common/GetAllInvoice",
  GetAllIMaterial:"Common/GetAllmaterialList",
  GetAllJobList:"Common/GetAllJobs",
  GetAllMstContactType:"Common/GetAllMstContactType",
  GetAllTax:"Common/GetAllTax",

  //Tanent
  Tenantlist: "Tenant/GetAll",
  TenantCreate: "Tenant/Create",
  TenantUpdate: "Tenant/Update",
  TenantDelete: "Tenant/Delete",
  TenantActiveInActive: "Tenant/ActiveInActive",
  //Sub Tanent
  SubTenant: "SubTenant/GetAll",
  SubTenantCreate: "SubTenant/Create",
  SubTenantUpdate: "SubTenant/Update",
  SubTenantDelete: "SubTenant/Delete",
  SubTenantActiveInActive: "SubTenant/ActiveInActive",
  //Roles
  Role: "Roles/GetAll",
  RoleCreate: "Roles/Create",
  RoleUpdate: "Roles/Update",
  RoleDelete: "Roles/Delete",
  RoleActiveInActive: "Roles/ActiveInActive",
  //Users
  User: "User/GetAll",
  UserCreate: "User/Create",
  UserUpdate: "User/Update",
  UserDelete: "User/Delete",
  UserActiveInActive: "User/ActiveInActive",
  //contract
  Contact: "Contact/GetAll",
  ContactCreate: "Contact/Create",
  ContactUpdate: "Contact/Update",
  ContactDelete: "Contact/Delete",
  ContactActiveInActive: "Contact/ActiveInActive",
  //Material
  Material: "Material/GetAll",
  MaterialCreate: "Material/Create",
  MaterialUpdate: "Material/Update",
  MaterialDelete: "Material/Delete",
  MaterialActiveInActive: "Material/ActiveInActive",
  //Component
  Component: "Component/GetAll",
  ComponentCreate: "Component/Create",
  ComponentUpdate: "Component/Update",
  ComponentDelete: "Component/Delete",
  ComponentActiveInActive: "Component/ActiveInActive",
  AddComponentMaterial: "Component/AddComponentMaterial",
  DeleteComponentMaterial: "Component/DeleteComponentMaterial",
  UpdateComponentMaterial: "Component/UpdateComponentMaterial",
  //Address
  Address: "Address/GetAll",
  AddressCreate: "Address/Create",
  AddressUpdate: "Address/Update",
  AddressDelete: "Address/Delete",
  AddressActiveInActive: "Address/ActiveInActive",
  //Vendor
  Vendor: "Vendor/GetAll",
  VendorCreate: "Vendor/Create",
  VendorUpdate: "Vendor/Update",
  VendorDelete: "Vendor/Delete",
  VendorActiveInActive: "Vendor/ActiveInActive",
  //Options
  Option: "Option/GetAll",
  OptionCreate: "Option/Create",
  OptionUpdate: "Option/Update",
  OptionDelete: "Option/Delete",
  OptionActiveInActive: "Option/ActiveInActive",
  //Product
  Product: "Product/GetAll",
  ProductCreate: "Product/Create",
  ProductUpdate: "Product/Update",
  ProductDelete: "Product/Delete",
  ProductActiveInActive: "Product/ActiveInActive",
  DeleteProductComponent: "Product/DeleteProductComponent",
  AddProductComponent: "Product/AddProductComponent",
  UpdateProductComponent: "Product/UpdateProductComponent",
  //Job
  Job: "Job/GetAll",
  JobCreate: "Job/Create",
  JobUpdate: "Job/Update",
  JobDelete: "Job/Delete",
  //taxes
  Tax: "Tax/GetAll",
  TaxCreate: "Tax/Create",
  TaxUpdate: "Tax/Update",
  TaxDelete: "Tax/Delete",
  TaxActiveInActive: "Tax/ActiveInActive",
  //window
  Window: "Window/GetAll",
  WindowCreate: "Window/Create",
  WindowUpdate: "Window/Update",
  WindowDelete: "Window/Delete",
  WindowActiveInActive: "Window/ActiveInActive",
  //Estimate/GetAll
  Estimate: "Estimate/GetAll",
  EstimateCreate: "Estimate/Create",
  EstimateUpdate: "Estimate/Update",
  EstimateDelete: "Estimate/Delete",
  EstimateActiveInActive: "Estimate/ActiveInActive",
  SendForApproval: "Estimate/SendForApproval",
  ViewEstimate: "Estimate/ViewEstimate",
  EstimateApproved: "Estimate/EstimateApproved",
  EstimationBreakdown:"Estimate/EstimationBreakdown",
  BuildEstimate:"Estimate/BuildEstimate",
  SendInvoice:"Invoice/SendInvoice",
  //discount
  Discount: "Discount/GetAll",
  DiscountCreate: "Discount/Create",
  DiscountUpdate: "Discount/Update",
  DiscountDelete: "Discount/Delete",
  DiscountActiveInActive: "Discount/ActiveInActive",
  //expression
  Expression: "Expression/GetAll",
  ExpressionCreate: "Expression/Create",
  ExpressionUpdate: "Expression/Update",
  ExpressionDelete: "Expression/Delete",
  ExpressionActiveInActive: "Expression/ActiveInActive",
  ExpressionValidate:"Expression/Validate",
  //Order
  OrderCreate: "Order/Create",
  Order:"Order/GetAll",
  orderSendForApproval:"Order/SendForApproval",
  OrderUpdate:"Order/Update",
  ViewOrder:"Order/ViewOrder",
  OrderApproved:"Order/OrderApproved",
  ViewHistory:"Order/ViewHistory",
  //Invoice
  Invoice:"Invoice/GetAll",
  InvoiceCreate:"Invoice/Create",
  InvoiceUpdate:"Invoice/Update",
  InvoiceDelete:"Invoice/Delete",
  InvoiceActiveInActive:"Invoice/ActiveInActive",

  //Payment
  Payment:"Payment/GetAll",
  PaymentCreate:"Payment/Create",
  PaymentUpdate:"Payment/Update",
  PaymentDelete:"Payment/Delete",
  PaymentActiveInActive:"Payment/ActiveInActive",
  //vendor Order
  VendorOrder:"VendorOrder/GetAll",
  VendorOrderCreate:"VendorOrder/Create",
  VendorOrderUpdate:"VendorOrder/Update",
  VendorOrderDelete:"VendorOrder/Delete",
  VendorOrderActiveInActive:"VendorOrder/ActiveInActive",
  updateVendorOrderItem:"VendorOrder/update_VendorOrderItem",
  deleteVendorOrderItem:"VendorOrder/delete_VendorOrderItem",
  //job schedule
  JobSchedule:"JobSchedule/GetAll",
  JobScheduleCreate:"JobSchedule/Create",
  JobScheduleUpdate:"JobSchedule/Update",
  JobScheduleDelete:"JobSchedule/Delete",
  JobScheduleActiveInActive:"JobSchedule/ActiveInActive",
  
  //contact
  JobContact:"JobContact/GetAll",
  JobContactCreate:"JobContact/Add",
  JobContactUpdate:"JobContact/Edit",
  JobContactDelete:"JobContact/Delete",
  JobContactActiveInActive:"JobContact/ActiveInActive",
  





};
